In [1]:
import tensorflow

In [2]:
import keras


Using TensorFlow backend.


In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
sent = ['the glass of milk', 'the glass of juice', 'the cup of tea', 'I am a good girl', 'I am a good developer',
       'understand the meaning of words', 'your viedeos are good']

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good girl',
 'I am a good developer',
 'understand the meaning of words',
 'your viedeos are good']

In [6]:
### vocabulary size
voc_size = 10000

### One Hot representation

In [8]:
onehot_repr = [one_hot(word, voc_size) for word in sent]
print(onehot_repr)

[[9140, 4671, 2989, 8063], [9140, 4671, 2989, 1142], [9140, 990, 2989, 1126], [5050, 158, 5468, 7108, 2404], [5050, 158, 5468, 7108, 2327], [3452, 9140, 7129, 2989, 8227], [9503, 2917, 1795, 7108]]


### Word enbeding representation

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences # all sentences must be the same length
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [12]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, padding = 'pre', maxlen = sent_length)
print(embedded_docs)

[[   0    0    0    0 9140 4671 2989 8063]
 [   0    0    0    0 9140 4671 2989 1142]
 [   0    0    0    0 9140  990 2989 1126]
 [   0    0    0 5050  158 5468 7108 2404]
 [   0    0    0 5050  158 5468 7108 2327]
 [   0    0    0 3452 9140 7129 2989 8227]
 [   0    0    0    0 9503 2917 1795 7108]]


In [13]:
dim = 10 # how many features

In [15]:
model = Sequential()
model.add(Embedding(voc_size, 10, input_length = sent_length))
model.compile('adam', 'mse')

In [16]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [17]:
print(model.predict(embedded_docs))

[[[-0.00779746  0.02206862 -0.04405114  0.03490165 -0.03228637
    0.01895794 -0.01597612  0.03094519  0.03705296  0.02434379]
  [-0.00779746  0.02206862 -0.04405114  0.03490165 -0.03228637
    0.01895794 -0.01597612  0.03094519  0.03705296  0.02434379]
  [-0.00779746  0.02206862 -0.04405114  0.03490165 -0.03228637
    0.01895794 -0.01597612  0.03094519  0.03705296  0.02434379]
  [-0.00779746  0.02206862 -0.04405114  0.03490165 -0.03228637
    0.01895794 -0.01597612  0.03094519  0.03705296  0.02434379]
  [-0.02709084  0.04901728 -0.0482283  -0.03644542 -0.02416729
   -0.00497771 -0.02205061 -0.01560266 -0.01578037 -0.00725967]
  [-0.04172134  0.01926578 -0.04186642  0.04181751  0.04318161
   -0.01566062 -0.04974343  0.00777446 -0.04643302  0.00235652]
  [-0.03140154  0.02897011  0.0178064   0.00901647 -0.04397231
    0.04574598  0.02035213  0.04432234 -0.00927998  0.04031327]
  [-0.0218629   0.01362878 -0.03472605  0.01798579 -0.0209224
   -0.02246885 -0.01026164  0.02181793 -0.0040136

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 9140, 4671, 2989, 8063])

In [19]:
print(model.predict(embedded_docs)[0])
# creating embedded matrix

[[-0.00779746  0.02206862 -0.04405114  0.03490165 -0.03228637  0.01895794
  -0.01597612  0.03094519  0.03705296  0.02434379]
 [-0.00779746  0.02206862 -0.04405114  0.03490165 -0.03228637  0.01895794
  -0.01597612  0.03094519  0.03705296  0.02434379]
 [-0.00779746  0.02206862 -0.04405114  0.03490165 -0.03228637  0.01895794
  -0.01597612  0.03094519  0.03705296  0.02434379]
 [-0.00779746  0.02206862 -0.04405114  0.03490165 -0.03228637  0.01895794
  -0.01597612  0.03094519  0.03705296  0.02434379]
 [-0.02709084  0.04901728 -0.0482283  -0.03644542 -0.02416729 -0.00497771
  -0.02205061 -0.01560266 -0.01578037 -0.00725967]
 [-0.04172134  0.01926578 -0.04186642  0.04181751  0.04318161 -0.01566062
  -0.04974343  0.00777446 -0.04643302  0.00235652]
 [-0.03140154  0.02897011  0.0178064   0.00901647 -0.04397231  0.04574598
   0.02035213  0.04432234 -0.00927998  0.04031327]
 [-0.0218629   0.01362878 -0.03472605  0.01798579 -0.0209224  -0.02246885
  -0.01026164  0.02181793 -0.00401368 -0.03799184]]